### ISSUE TITLE
Incompatibility with ember-cli.

### ISSUE THREAD

**Issue by cibernox** [ryanflorence/broccoli-es6-module-filter#8]
I was trying to use `broccoli-dist-es6-module` in the brocfile of an ember-cli project and I got this error:

```
$ ember build
version: 0.1.1
Building...
Invalid access to private name
Error: Invalid access to private name
    at Error (<anonymous>)
    at assertNotName (/Users/miguel/code/ember-cpm/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:201:13)
    at defineProperty (/Users/miguel/code/ember-cpm/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:256:7)
    at new Name (/Users/miguel/code/ember-cpm/node_modules/broccoli-dist-es6-module/node_modules/broccoli-es6-module-filter/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:103:5)
    at /Users/miguel/code/ember-cpm/node_modules/broccoli-dist-es6-module/node_modules/broccoli-es6-module-filter/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:134:27
    at Object.<anonymous> (/Users/miguel/code/ember-cpm/node_modules/broccoli-dist-es6-module/node_modules/broccoli-es6-module-filter/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:539:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I've tracked down the problem to here: https://github.com/rpflorence/broccoli-es6-module-filter/blob/master/package.json#L22

The problems seems to be that [es6-module-transpiler](https://github.com/esnext/es6-module-transpiler) whet though a major rewrite in 0.5 version. The old version was quite buggy and collided with other packages, which is my exact issue. This is project is using a fork started out before that rewrite, but probably for a good reason.

Can I get more insight of why are we using a fork. I might be able to help.

**Comment by givanse** [comment]
Just stumbled upon this too. The reason to use a fork is this: https://github.com/rpflorence/es6-module-transpiler/compare/broccoli However, I'm still trying to wrap my head around it.

The projects `broccoli-es6-module-filter`, `broccoli-dist-es6-module` and the fork The fork `es6-module-transpiler#broccoli`  were last updated 9 months ago (~21 February).

Aside from time constraints, do you think those projects have a chance to catch up with `es6-module-transpiler`? I mean, is it viable?

**Comment by givanse** [comment]
The fork of `es6-module-transpiler` was done from **v0.2.0** and the last version until now is **v0.9.5**. So, probably it is easier to do a rewritte from scratch than to update.

Looks like the seat will be taken by `broccoli-es6-module-transpiler`.
